FROM python:3.10-slim

# Install required packages
RUN apt-get update && apt-get install -y git && apt-get clean
RUN pip install --no-cache-dir transformers torch flask rembg

# Copy the app
WORKDIR /app
COPY model_service.py .

# Expose port and run the model service
EXPOSE 5001
CMD ["python", "model_service.py"]